// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WelcomeSite.Data;

namespace WelcomeSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210216132545_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WelcomeSite.Respondent", b =>
                {
                    b.Property<Guid>("RespondentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RespondentCreatedDateTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RespondentID");

                    b.ToTable("Respondents");
                });

            modelBuilder.Entity("WelcomeSite.SurveyQuestion", b =>
                {
                    b.Property<Guid>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("QuestionCreatedDateTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("QuestionIsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionID");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("WelcomeSite.SurveyResponse", b =>
                {
                    b.Property<Guid>("ResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RespondentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ResponseCreatedDateTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResponseText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResponseID");

                    b.ToTable("SurveyResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
