name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest    

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: cd WelcomeSite; docker build . --file Dockerfile --tag welcome-site:$(date +%s)

#   publish:
#     needs: build
#     runs-on: ubuntu-latest
    environment: Azure
    
    steps:
      - uses: actions/checkout@master
      - name: Login to ACR
        id: ecr
        uses: elgohr/acr-login-action@master
        with:
          service_principal: ${{ secrets.AZURE_USER }}
          service_principal_password: ${{ secrets.AZURE_PASSWORD }}
          tenant: ${{ secrets.AZURE_TENANT }}
          registry: https://welcomesitecontainer.azurecr.io
          repository: welcomesitecontainer
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: welcome-site
          username: ${{ steps.ecr.outputs.username }}
          password: ${{ steps.ecr.outputs.password }}
          registry: https://welcomesitecontainer.azurecr.io
#       - name: Publish Docker
#         uses: elgohr/Publish-Docker-Github-Action@master
#         with:
#           name: welcomesitecontainer.azurecr.io
#           username: ${{ secrets.AZURE_USER }}
#           password: ${{ secrets.AZURE_PASSWORD }}
#           tenant: ${{ secrets.AZURE_TENANT }}
#           registry: welcomesitecontainer
#           repository: welcomesitecontainer
#           image: welcome-site
#           git_access_token: ${{ secrets.GITHUB_TOKEN }}
#           folder: WelcomeSite
#           dockerfile: Dockerfile
