name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: sharpninja/Publish-Docker-Github-Action@testing
        env:
          ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
        with:
          name: welcome-site
          username: ${{ secrets.AZURE_USER }}
          password: ${{ secrets.AZURE_PASSWORD }}
          registry: https://welcomesitecontainer.azurecr.io
