name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: sharpninja/Publish-Docker-Github-Action@testing
        env:
          ACTIONS_STEP_DEBUG: false
          name: welcome-site
          username: ${{ secrets.AZURE_USER }}
          password: ${{ secrets.AZURE_PASSWORD }}
          tenantId: ${{ secrets.AZURE_TENANT }}
          registry_url: https://welcomesitecontainer.azurecr.io
          context: ./WelcomeSite
