name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd WelcomeSite; docker build . --file Dockerfile --tag welcome-site:$(date +%s)

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: Azure
    
    steps:
    - name: Publish Docker
      # You may pin to the exact commit or the version.
      # uses: elgohr/Publish-Docker-Github-Action@f7aca2fea76a5218f3c76cd5933c3ba1d8008774
      uses: ams0/acr-task-github-action@v2
      with:
        service_principal: ${{ secrets.AZURE_USER }}
        service_principal_password: ${{ secrets.AZURE_PASSWORD }}
        tenant: ${{ secrets.AZURE_TENANT }}
        registry: welcomesitecontainer
        repository: welcomesitecontainer
        image: welcome-site
        git_access_token: ${{ secrets.GITHUB_TOKEN }}
        folder: WelcomeSite
        dockerfile: Dockerfile
